/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package agcoopsys;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class addCompany extends javax.swing.JFrame {

    private String companyName;
    private String companyAddress1;
    private String companyAddress2;
    private String companyAddress3;
    private String companyEmail;
    private String companyContactPerson;
    private String companyContact1;
    private String companyContact2;
    ConnectToDatabaseSys paramDB = new ConnectToDatabaseSys();
    public String dbUrl;
    public String dbDriver;
    public String username;
    public String password;
    public Connection conn;
    int companyID;
    int choice = 0;
    
    validateAllInputs validateInputs = new validateAllInputs();
    
    public addCompany() {
        initComponents();
    }

    public void setCompanyAddress1() {
        this.companyAddress1 = textCompanyAd1.getText();
    }

    public void setCompanyAddress2() {
        this.companyAddress2 = textCompanyAd2.getText();
    }

    public void setCompanyAddress3() {
        this.companyAddress3 = textCompanyAd3.getText();
    }

    public void setCompanyContact1() {
        this.companyContact1 = textCompanyContact1.getText();
    }

    public void setCompanyContact2() {
        this.companyContact2 = textCompanyContact1.getText();
    }

    public void setCompanyContactPerson() {
        this.companyContactPerson = textCompanyContactPerson.getText();
    }

    public void setCompanyEmail() {
        this.companyEmail = textCompanyEmail.getText();
    }

    public void setCompanyName() {
        this.companyName = textCompanyName.getText();
    } 
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textCompanyName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textCompanyEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textCompanyContactPerson = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textCompanyContact1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textCompanyContact2 = new javax.swing.JTextField();
        buttonConfirm = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        textCompanyAd3 = new javax.swing.JTextField();
        textCompanyAd2 = new javax.swing.JTextField();
        textCompanyAd1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Company name");

        jLabel5.setText("E-mail");

        jLabel6.setText("Contact Person");

        jLabel7.setText("Contact No. 1");

        jLabel8.setText("Contact No. 2");

        buttonConfirm.setText("Confirm");
        buttonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonClear.setText("Clear");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));

        textCompanyAd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCompanyAd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCompanyAd1)
                    .addComponent(textCompanyAd3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textCompanyAd2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textCompanyAd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(textCompanyAd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCompanyAd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(buttonCancel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonConfirm))
                            .addComponent(textCompanyContact2)
                            .addComponent(textCompanyContact1)
                            .addComponent(textCompanyEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(textCompanyContactPerson, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textCompanyName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCompanyEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCompanyContactPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCompanyContact1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCompanyContact2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonConfirm)
                    .addComponent(buttonCancel)
                    .addComponent(buttonClear))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmActionPerformed

        this.setCompanyAddress1();
        this.setCompanyAddress2();
        this.setCompanyAddress3();
        this.setCompanyContact1();
        this.setCompanyContact2();
        this.setCompanyContactPerson();
        this.setCompanyEmail();
        this.setCompanyName();
        this.checkInputAddCompany();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonConfirmActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed

        this.reset();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClearActionPerformed

    public void reset()
    {
        textCompanyName.setText("");
        textCompanyAd1.setText("");
        textCompanyAd2.setText("");
        textCompanyAd3.setText("");
        textCompanyEmail.setText("");
        textCompanyContactPerson.setText("");
        textCompanyContact1.setText("");
        textCompanyContact2.setText("");
    }
    
    private void textCompanyAd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCompanyAd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCompanyAd1ActionPerformed

    public void checkInputAddCompany()
    {
        String errorMessages = "";
        ConnectToDatabaseSys connectDB = new ConnectToDatabaseSys();
        int errorCount = 0;
        //FORMAT
        companyAddress1 = validateInputs.formatStringSpaces(companyAddress1);
        companyAddress2 = validateInputs.formatStringSpaces(companyAddress2);
        companyAddress3 = validateInputs.formatStringSpaces(companyAddress3);
        companyContactPerson = validateInputs.formatStringSpaces(companyContactPerson);
        companyName = validateInputs.formatStringSpaces(companyName);
        //THEN CHECK
        
        try
        {
            if(!(connectDB.checkDuplicate(companyName, 1)))
            {
                errorMessages += "Company Name: Already exists\n";
                errorCount++;
            }
        }
        catch(Exception t)
        {
            errorMessages += "Company Name: Already exists\n";
            errorCount++;
        }
        
        if(textCompanyContactPerson.toString().length() != 0)
        if(!(validateInputs.checkForSpecial(companyContactPerson)))
        {
            errorMessages += "Contact Person: Cannot Contain special characters\n";
            errorCount++;
        }      
        
        if(!(validateInputs.checkIfEmpty(companyName)))
        {
            errorMessages += "Company Name: Field cannot be empty\n";
            errorCount++;
        }
                
        if(errorCount == 0)
        {
                String query = "";
                if(choice == 0)
                {
                    query = "insert into company (compname,address1,address2,address3,contactperson,contactno1,contactno2,email)"
                            + " values ('"+ companyName +"','"+ companyAddress1 + "','" + companyAddress2 + "','" + companyAddress3 + "','"
                            + companyContactPerson + "','" + companyContact1 + "','" + companyContact2 + "','" + companyEmail + "')";
                }
                if(choice == 1)
                {
                    query = "update company set compname='"+ companyName +"',address1='"+ companyAddress1+"',address2='"+companyAddress2+"',address3='"+companyAddress3+"'"+
                            ",contactperson='"+companyContactPerson+"',contactno1='"+companyContact1+"',contactno2='"+companyContact2+"',email='"+companyEmail+"' where compid="+companyID;                            
                    choice = 0;
                }
                //System.out.println(query);
                connectDB.accessInputDatabase(query);
        }
        
        else if(errorCount>0)
        {
            System.out.println(errorMessages);
            JOptionPane.showMessageDialog(null, errorMessages, "Error: Company Information", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    public Connection getConnection()
    {
	return conn;
    }
        
    public void connect()
    {
        dbDriver = paramDB.getDbClass();
        dbUrl = paramDB.getDbUrl();
        password = paramDB.getPassword(); // CHANGE PASSWORD
        username = paramDB.getName();
                
        try
        {
            Class.forName(dbDriver).newInstance();
            conn = DriverManager.getConnection(dbUrl,username,password);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
	
    public void disconnect()
    {
       try
       {
            conn.close();
       } 
       catch (Exception ex)
       {
            ex.printStackTrace();
       }
    }
    
    public void checkInputEditCompany(String id)
    {
        ResultSet rs;
        this.connect();
        Statement stmt = null;
        
        String query = "select * from company where compid="+id;
        
        try
        {
            stmt = conn.createStatement();
        }
                
	catch (SQLException e)
        {
            e.printStackTrace();
        }
        
        try
        {
            rs = stmt.executeQuery(query);
            if(rs.next())
            {
                textCompanyName.setText(rs.getString("compname"));
                textCompanyAd1.setText(rs.getString("address1"));
                textCompanyAd2.setText(rs.getString("address2"));
                textCompanyAd3.setText(rs.getString("address3"));
                textCompanyContactPerson.setText(rs.getString("contactperson"));
                textCompanyContact1.setText(rs.getString("contactno1"));
                textCompanyContact2.setText(rs.getString("contactno2"));
                textCompanyEmail.setText(rs.getString("email")); 
                companyID = rs.getInt("compid");
            }
            this.disconnect();      
	}
        
        catch (SQLException e)
        {
            e.printStackTrace();
	}   
        choice = 1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCompany().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textCompanyAd1;
    private javax.swing.JTextField textCompanyAd2;
    private javax.swing.JTextField textCompanyAd3;
    private javax.swing.JTextField textCompanyContact1;
    private javax.swing.JTextField textCompanyContact2;
    private javax.swing.JTextField textCompanyContactPerson;
    private javax.swing.JTextField textCompanyEmail;
    private javax.swing.JTextField textCompanyName;
    // End of variables declaration//GEN-END:variables
}
