/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package agcoopsys;

import java.awt.Component;
import java.awt.Container;
import java.awt.FocusTraversalPolicy;
import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class addMember extends javax.swing.JFrame {

    private String memberFirstName;
    private String memberLastName;
    private String memberMiddleName;
    private String memberAddress1;
    private String memberAddress2 = "";
    private String memberAddress3 = "";
    private String memberContact1;
    private String memberContact2;
    private String memberEmail;
    private float memberContribution;
    private float memberTotal = 0;
    private float memberShares;
    private String memberEmploymentStatus = "";
    
    private Date memberHired;
    private Date memberResigned;
    
    private String memberHiredText;
    private String memberResignedText;
    private String memberRemarks;
    private String memberContriText;
    private String memberTotalText;
    private String memberSharesText;
    private String companyIDText;
    private String finalHired;
    private String finalResigned = "";
    private int companyID;
    private int memberID;
    DateFormat df; 
    ArrayList<Integer> arrayList = new ArrayList<>();
    ArrayList<String> arrayListCompany = new ArrayList<>();
    
    validateAllInputs validateInputs = new validateAllInputs();
    int choice = 0;
    public String dbUrl;
    public String dbDriver;
    public String username;
    public String password;
    public Connection conn;
    ConnectToDatabaseSys paramDB = new ConnectToDatabaseSys();
    
    
    public addMember()
    {
        this.df = new SimpleDateFormat("yyyy-MM-dd");
        df.setLenient(false);
        initComponents();
        this.returnParams();
        buttonGroup.add(radioEmployed);
        buttonGroup.add(radioResigned);
        radioEmployed.setSelected(true);
        Calendar cal = Calendar.getInstance();
        Date current = new Date();
        current = cal.getTime();
        textDateHired.setText(df.format(current));
    }

    
    public void setCompanyIDText(String companyIDText) {
        this.companyIDText = (String) comboCompany.getSelectedItem();
    }
    
    public void setMemberAddress1() {
        this.memberAddress1 = textMemAd1.getText();
    }

    public void setMemberAddress2() {
        this.memberAddress2 = textMemAd2.getText();
    }

    public void setMemberAddress3() {
        this.memberAddress3 = textMemAd3.getText();
    }

    public void setMemberContact1() {
        this.memberContact1 = textMemCon1.getText();
    }

    public void setMemberContact2() {
        this.memberContact2 = textMemCon2.getText();
    }

    public void setMemberContriText() {
        this.memberContriText = textContribution.getText();
    }

    public void setMemberEmail() {
        this.memberEmail = textMemEmail.getText();
    }

    public void setMemberEmploymentStatus() {
        if(radioEmployed.isSelected())
            memberEmploymentStatus = "E";
        else if(radioResigned.isSelected())
            memberEmploymentStatus = "R";
    }

    public void setMemberFirstName() {
        this.memberFirstName = textFirstName.getText();
    }

    public void setMemberHired(Date memberHired) {
        this.memberHired = memberHired;
    }

    public void setMemberLastName() {
        this.memberLastName = textLastName.getText();
    }

    public void setMemberMiddleName() {
        this.memberMiddleName = textMidInit.getText();
    }

    public void setMemberRemarks() {
        this.memberRemarks = textRemark.getText();
    }

    public void setMemberResigned(Date memberResigned) {
        this.memberResigned = memberResigned;
    }

    public void setMemberShareText() {
        this.memberSharesText = textShare.getText();
    }

    public void setMemberTotalText() {
        this.memberTotalText = textTotal.getText();
    }

    public void setMemberHiredText() {
        this.memberHiredText = textDateHired.getText();
    }
    
    public void setMemberResignedTexT(){
        this.memberResignedText = textDateResigned.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        textFirstName = new javax.swing.JTextField();
        textMidInit = new javax.swing.JTextField();
        textLastName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textShare = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textContribution = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        radioEmployed = new javax.swing.JRadioButton();
        radioResigned = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textRemark = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        textMemEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textMemCon1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textMemCon2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboCompany = new javax.swing.JComboBox();
        buttonConfirm = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        textDateHired = new javax.swing.JTextField();
        textDateResigned = new javax.swing.JTextField();
        buttonClear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        textMemAd3 = new javax.swing.JTextField();
        textMemAd2 = new javax.swing.JTextField();
        textMemAd1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel14.setText("Max share");

        textTotal.setEditable(false);
        textTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textTotal.setText("0");

        jLabel15.setText("Status");

        textShare.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textShare.setText("0");
        textShare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textShareActionPerformed(evt);
            }
        });

        jLabel12.setText("Contribution");

        jLabel13.setText("Total");

        textContribution.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textContribution.setText("0");

        jLabel3.setText("First name");

        jLabel4.setText("Middle Initial");

        radioEmployed.setText("Employed");
        radioEmployed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioEmployedStateChanged(evt);
            }
        });
        radioEmployed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioEmployedItemStateChanged(evt);
            }
        });

        radioResigned.setText("Resigned");
        radioResigned.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioResignedStateChanged(evt);
            }
        });
        radioResigned.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioResignedItemStateChanged(evt);
            }
        });

        jLabel5.setText("Last name");

        jLabel17.setText("Date resigned");
        jLabel17.setEnabled(false);

        jLabel18.setText("Remarks");

        textRemark.setColumns(20);
        textRemark.setRows(5);
        jScrollPane1.setViewportView(textRemark);

        jLabel16.setText("Date hired");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel9.setText("Contact No. 1");

        jLabel10.setText("Contact No. 2");

        jLabel11.setText("E-mail");

        jLabel1.setText("Company");

        buttonConfirm.setText("Confirm");
        buttonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        textDateResigned.setEnabled(false);

        buttonClear.setText("Clear");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));

        textMemAd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMemAd3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textMemAd3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(textMemAd2)
                    .addComponent(textMemAd1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(textMemAd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textMemAd2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textMemAd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(39, 39, 39)
                                .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFirstName)
                                    .addComponent(textMidInit, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                    .addComponent(comboCompany, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textMemCon2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textMemEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textMemCon1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(radioEmployed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioResigned))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textDateResigned, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(textDateHired)))))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textShare)
                            .addComponent(textTotal)
                            .addComponent(textContribution, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonClear)
                        .addGap(57, 57, 57)
                        .addComponent(buttonConfirm)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textMidInit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMemCon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textMemCon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMemEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(textContribution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(textShare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(radioEmployed)
                    .addComponent(radioResigned))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(textDateHired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(textDateResigned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonConfirm)
                    .addComponent(buttonClear)
                    .addComponent(buttonCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textMemAd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMemAd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMemAd3ActionPerformed

    private void buttonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmActionPerformed

        this.setMemberAddress1();
        this.setMemberAddress2();
        this.setMemberAddress3();
        this.setMemberContact1();
        this.setMemberContact2();
        this.setMemberContriText();
        this.setMemberEmploymentStatus();
        this.setMemberEmail();
        this.setMemberFirstName();
        this.setMemberLastName();
        this.setMemberMiddleName();
        this.setMemberRemarks();
        this.setMemberShareText();
        this.setMemberTotalText();
        this.setMemberHiredText();
        this.setMemberResignedTexT();
        
        this.checkInputAddMember();

        // TODO add your handling code here:
    }//GEN-LAST:event_buttonConfirmActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void radioEmployedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioEmployedStateChanged


        // TODO add your handling code here:
    }//GEN-LAST:event_radioEmployedStateChanged

    private void radioResignedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioResignedStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_radioResignedStateChanged

    private void radioResignedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioResignedItemStateChanged
        jLabel17.setEnabled(true);
        textDateResigned.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_radioResignedItemStateChanged

    private void radioEmployedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioEmployedItemStateChanged
        jLabel17.setEnabled(false);
        textDateResigned.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEmployedItemStateChanged

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        
        this.reset();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClearActionPerformed

    public void reset()
    {
        Calendar cal = Calendar.getInstance();
        Date current = new Date();
        current = cal.getTime();
        textFirstName.setText("");
        textLastName.setText("");
        textMidInit.setText("");
        textMemAd1.setText("");
        textMemAd2.setText("");
        textMemAd3.setText("");
        textMemCon1.setText("");
        textMemCon2.setText("");
        textMemEmail.setText("");
        textContribution.setText("0");
        textShare.setText("0");
        textTotal.setText("0");
        textDateHired.setText(df.format(current));
        textDateResigned.setText("");
        textRemark.setText("");
        radioEmployed.setSelected(true);
        radioResigned.setSelected(false);
    }
    
    private void textShareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textShareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textShareActionPerformed

    public void checkInputAddMember()
    {
        String errorMessages = "";
        int errorCount = 0;
        
        //FORMAT
        memberFirstName = validateInputs.formatStringSpaces(memberFirstName);
        memberLastName = validateInputs.formatStringSpaces(memberLastName);
        memberMiddleName = validateInputs.formatStringSpaces(memberMiddleName);
        memberAddress1 = validateInputs.formatStringSpaces(memberAddress1);
        memberAddress2 = validateInputs.formatStringSpaces(memberAddress2);
        memberAddress3 = validateInputs.formatStringSpaces(memberAddress3);
        memberRemarks = validateInputs.formatStringSpaces(memberRemarks);     
        
        
        //CHECK
        if(!(validateInputs.checkForSpecial(memberFirstName)))
        {
            errorMessages += "First Name: Field cannot contain special characters\n";
            errorCount++;
        }
        
        if(!(validateInputs.checkForSpecial(memberLastName)))
        {
            errorMessages += "Last Name: Field cannot contain special characters\n";
            errorCount++;
        }
        
        if(!(validateInputs.checkIfMiddleInitial(memberMiddleName)))
        {
            errorMessages += "Middle Initial: Should not contain special characters and should only have one character\n";
            errorCount++;
        }
        
        if(!(validateInputs.checkIfEmpty(memberFirstName)))
        {
            errorMessages += "First Name: Field cannot be empty\n";
            errorCount++;
        }
        
        if(!(validateInputs.checkIfEmpty(memberLastName)))
        {
            errorMessages += "Last Name: Field cannot be empty\n";
            errorCount++;
        }
        
        if(!(validateInputs.checkIfEmpty(memberMiddleName)))
        {
            errorMessages += "Middle Initial: Field cannot be empty\n";
            errorCount++;
        }
                
        try
        {
            memberContribution = Float.parseFloat(memberContriText);
        }
        
        catch(Exception e)
        {
            errorMessages += "Contribution: Field should only contain numbers\n";
            errorCount++;
        }
        
        try
        {
            memberShares = Float.parseFloat(memberSharesText);
        }
        
        catch(Exception e)
        {
            errorMessages += "Shares: Field should only contain numbers\n";
            errorCount++;
        }
        
        try
        {  
            memberHired = df.parse(memberHiredText);
            finalHired = df.format(memberHired);
            System.out.println(finalHired);
        } 
        catch (Exception p)
        { 
            errorMessages += "Date Hired: Format YYYY-MM-DD\n";
            errorCount++;
            System.out.println(finalHired);
        } 
        
        try
        {
            companyID = this.getCompanyIdCombo(comboCompany.getSelectedIndex());
        }
        
        catch(Exception m)
        {
            errorMessages += "Company: No company selected\n";
            errorCount++;
        }
        
        if(textDateResigned.getText().length() != 0)
        {
            try
            {  
                memberResigned = (Date) df.parse(memberResignedText);
                finalResigned = df.format(memberResigned);
            } 
            catch (Exception q)
            { 
                errorMessages += "Date Resigned: Format YYYY-MM-DD\n";
                errorCount++;
            }
            
        }
        
        //THEN COMMIT
        if(errorCount == 0)
        {
            String query = "";
            if(choice == 0)
            {
                query = "insert into member (firstname,midinit,lastname,address1,address2,address3,contactno1,contactno2,email,compid,contribution,contribtotal,maxshare,status,hiredt,resigndt,remarks)"
                    + " values " + "('" + memberFirstName + "','" + memberMiddleName + "','" + memberLastName + "','" + memberAddress1 + "','" + memberAddress2 +"','"+ memberAddress3
                    +"','"+ memberContact1 + "','"+ memberContact2 + "','"+memberEmail+"','"+ companyID +"','"+ memberContribution + "','"+ memberTotal+ "','"+memberShares+"','"+memberEmploymentStatus
                    +"','"+finalHired+"','"+finalResigned+"','"+memberRemarks+"')";
            }
            if(choice == 1)
            {
                query = "update member set firstname='"+memberFirstName+"',midinit='"+memberMiddleName+"',lastname='"+memberLastName+"',address1='"+memberAddress1+",address2='"+memberAddress2+"',address3='"+memberAddress3+"',contactno1='"+
                        memberContact1+"',contactno2='"+memberContact2+"',email='"+memberEmail+"',compid='"+companyID+"',contribution='"+memberContribution+"',contribtotal='"+memberTotal+"',maxshare='"+memberShares+"',status='"+memberEmploymentStatus+"',hiredt='"+
                        memberHired+"',resigndt='"+memberResigned+"',remarks='"+memberRemarks+"' where memberid="+memberID;
            }
            choice = 0;
            //System.out.println(query);
            ConnectToDatabaseSys connectDB = new ConnectToDatabaseSys();
            connectDB.accessInputDatabase(query);
            viewMember vM = new viewMember();
            vM.getList();
        }
        else if(errorCount>0)
        {
            //System.out.println(errorMessages);
            JOptionPane.showMessageDialog(null, errorMessages, "Error: Member Information", JOptionPane.ERROR_MESSAGE);
        }   
    }

    public int getCompanyIdCombo(int comboID)
    {
        int companyID = 0;
        companyID = arrayList.get(comboID);
        return companyID;
    }
    
    public void initComboEdit(int memid)
    {
        for(int i = 0; i<arrayList.size(); i++)
        {
            System.out.println(memid +" : "+ arrayList.get(i));;
            if(memid == arrayList.get(i))
            {
                comboCompany.setSelectedItem(arrayListCompany.get(i));
            }
        }
    }
    
    public void initDateHired(String hiredt) throws ParseException
    {
           Date Hired = df.parse(hiredt);
           String sHired = df.format(Hired);
           textDateHired.setText(sHired);
    }
    
    public void initDateResigned(String resigndt) throws ParseException
    {
           Date Resign = df.parse(resigndt);
           String sResign = df.format(Resign);
           textDateHired.setText(sResign);
    }
    
    public void initRadioEdit(String status)
    {
        if(status.equals("E"))
        {
            radioEmployed.setSelected(true);
        }
        else
            radioResigned.setSelected(true);
            
    }
    
    public void returnParams()
    {        
        final String query = "select compid, compname from company order by compname";
        
        ResultSet rs;
        this.connect();
        Statement stmt = null;
        
        try
        {
            stmt = conn.createStatement();
        }
                
	catch (SQLException e)
        {
            e.printStackTrace();
        }
        
        try
        {
            companyList compList = new companyList();
            rs = stmt.executeQuery(query);
            int index = 0;
            while(rs.next())
            {
                comboCompany.addItem(rs.getString("compname"));
                System.out.println(rs.getInt("compid") + " : " + rs.getString("compname"));
                arrayList.add(rs.getInt("compid"));
                arrayListCompany.add(rs.getString("compname"));
            }
            this.disconnect();      
	}
        
        catch (SQLException e)
        {
            e.printStackTrace();
	}   
    }
       
    public void connect()
    {
        dbDriver = paramDB.getDbClass();
        dbUrl = paramDB.getDbUrl();
        password = paramDB.getPassword(); // CHANGE PASSWORD
        username = paramDB.getName();
                
        try
        {
            Class.forName(dbDriver).newInstance();
            conn = DriverManager.getConnection(dbUrl,username,password);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
        
    public Connection getConnection()
    {
	return conn;
    }
	
    public void disconnect()
    {
       try
       {
            conn.close();
       } 
       catch (Exception ex)
       {
            ex.printStackTrace();
       }
    }
    
    
    public void checkInputEditMember(String id)
    {
        ResultSet rs;
        this.connect();
        Statement stmt = null;
        String query = "select * from member where memberid="+id;
        
        try
        {
            stmt = conn.createStatement();
        }
                
	catch (SQLException e)
        {
            e.printStackTrace();
        }
        String tempHired = "";
        String tempResigned = "";
        try
        {
            rs = stmt.executeQuery(query);
            if(rs.next())
            {
                textFirstName.setText(rs.getString("firstname"));
                textLastName.setText(rs.getString("lastname"));
                textMidInit.setText(rs.getString("midinit"));
                textMemAd1.setText(rs.getString("address1"));
                textMemAd2.setText(rs.getString("address2"));
                textMemAd3.setText(rs.getString("address3"));
                textMemCon1.setText(rs.getString("contactno1"));
                textMemCon2.setText(rs.getString("contactno2"));
                textMemEmail.setText(rs.getString("email"));
                this.initComboEdit(rs.getInt("compid"));
                textContribution.setText(rs.getString("contribution"));
                textTotal.setText(rs.getString("contribtotal"));
                tempHired = rs.getString("hiredt");
                tempResigned = rs.getString("resigndt");
                textRemark.setText(rs.getString("remarks"));
                this.initRadioEdit(rs.getString("status"));
                memberID = rs.getInt("memberid");
            }
            this.disconnect();      
	}
        
        catch (SQLException e)
        {
	}   
        choice = 1;
        try{
            this.initDateHired(tempHired);
            this.initDateResigned(tempResigned);
        }
        catch(Exception e)
        {
            
        }
    }

    
    
    /**
     * @  param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addMember().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonConfirm;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox comboCompany;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton radioEmployed;
    private javax.swing.JRadioButton radioResigned;
    private javax.swing.JTextField textContribution;
    private javax.swing.JTextField textDateHired;
    private javax.swing.JTextField textDateResigned;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textMemAd1;
    private javax.swing.JTextField textMemAd2;
    private javax.swing.JTextField textMemAd3;
    private javax.swing.JTextField textMemCon1;
    private javax.swing.JTextField textMemCon2;
    private javax.swing.JTextField textMemEmail;
    private javax.swing.JTextField textMidInit;
    private javax.swing.JTextArea textRemark;
    private javax.swing.JTextField textShare;
    private javax.swing.JTextField textTotal;
    // End of variables declaration//GEN-END:variables
}
