/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package agcoopsys;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class viewNonMember extends javax.swing.JPanel {

    /**
     * Creates new form viewNonMember
     */
    public viewNonMember() {
        initComponents();
        listMember.getTableHeader().setReorderingAllowed(false);
    }
    
    ConnectToDatabaseSys paramDB = new ConnectToDatabaseSys();
    public String dbUrl;
    public String dbDriver;
    public String username;
    public String password;
    public Connection conn;
    DbUtils tableUtils = new DbUtils();
    int rep = 0;
    String query = "Select memberid,lastname,firstname,midinit,nonmember.contactno1,nonmember.contactno2,nonmember.email,compname from nonmember inner join company on nonmember.compid = company.compid order by lastname";

    public void getList()
    {
        String tempQuery = "";
        if(rep==0)
        {
            tempQuery = query;
        }
        //else
          //  tempQuery = "Select * from mydb.bookinformation where Title like '%"+bookTitle+"%';";
        
        //System.out.println(tempQuery);
	Statement stmt = null;       
	this.connect();
	conn = this.getConnection();
                
	try
        {
            stmt = conn.createStatement();
        }
                
	catch (SQLException e)
        {
            e.printStackTrace();
        }
		
	ResultSet rs;
	try
        {
            rs = stmt.executeQuery(tempQuery);
            try {
                tableUtils.updateTableModelData((DefaultTableModel) listMember.getModel(), rs, 8);
            } catch (Exception ex) {
                Logger.getLogger(viewMember.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        catch (SQLException e)
        {
            e.printStackTrace();
	}
        finally{
            this.disconnect();
        }
        try{
            listMember.setRowSelectionInterval(0, 0);
        }
        catch(Exception e)
        {
            
        }
        
    }
    
        public void deleteNonMember()
    {
        try
        {
            int index = listMember.getSelectedRow();
            String i = listMember.getValueAt(index, 0).toString();
        
            String query = "delete from nonmember where memberid ="+i;
            ConnectToDatabaseSys connectDB = new ConnectToDatabaseSys();
            connectDB.accessLoopDatabase(query);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error: Select row to delete", "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }
        
        public void editMember() 
    {
            int index = listMember.getSelectedRow();
            String i = listMember.getValueAt(index, 0).toString();
            addNonMember aM = new addNonMember();
            aM.setVisible(true);
            aM.setLocationRelativeTo(null);
            aM.setResizable(false);
            aM.setTitle("Edit Member - Information");
            aM.checkInputEditMember(i);
    }
    
    public void connect()
    {
        dbDriver = paramDB.getDbClass();
        dbUrl = paramDB.getDbUrl();
        password = paramDB.getPassword(); // CHANGE PASSWORD
        username = paramDB.getName();
                
        try
        {
            Class.forName(dbDriver).newInstance();
            conn = DriverManager.getConnection(dbUrl,username,password);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
	
    public Connection getConnection()
    {
	return conn;
    }
	
    public void disconnect()
    {
       try
       {
            conn.close();
       } 
       catch (Exception ex)
       {
            ex.printStackTrace();
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listMember = new javax.swing.JTable();

        listMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "LASTNAME", "FIRSTNAME", "MIDINIT", "CONTACTNO1", "CONTACTNO2", "E-MAIL", "COMPANY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listMember);
        listMember.getColumnModel().getColumn(0).setResizable(false);
        listMember.getColumnModel().getColumn(0).setPreferredWidth(30);
        listMember.getColumnModel().getColumn(1).setResizable(false);
        listMember.getColumnModel().getColumn(2).setResizable(false);
        listMember.getColumnModel().getColumn(3).setResizable(false);
        listMember.getColumnModel().getColumn(4).setResizable(false);
        listMember.getColumnModel().getColumn(6).setResizable(false);
        listMember.getColumnModel().getColumn(7).setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listMember;
    // End of variables declaration//GEN-END:variables
}
