/*
 * Start.java
 *
 * Created on September 22, 2008, 8:23 AM
 */

package agcoopsys;

import maininterface.MainInterface;
import mainconnect.ConnectToDatabaseSys;
import javax.sql.rowset.CachedRowSet;



public class Start extends javax.swing.JFrame  {
    
    private int i, j, error, idNo;
    private ConnectToDatabaseSys db;
    private CachedRowSet row;
    private String user, pass;
    private int userType; //REMOVE AFTER TEST
    
    /** Creates new form Start */
    public Start() {
        
       
        initComponents();
        this.setLocationRelativeTo(null);
       
        user = "";
        pass = "";
        
        
        error=1;
        userType = 1; //REMOVE AFTER TEST
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        ExitChange = new javax.swing.JButton();
        fieldUser = new javax.swing.JTextField();
        fieldPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonLogIn = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jDialog1.setResizable(false);

        jLabel13.setText("Wrong Username/Password! Please try again!");

        ExitChange.setText("OK");
        ExitChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(ExitChange))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel13)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(27, 27, 27)
                .addComponent(ExitChange)
                .addGap(37, 37, 37))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        fieldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPassActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setText("Password:");

        buttonLogIn.setText("Log In");
        buttonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogInActionPerformed(evt);
            }
        });

        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo450x90.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(buttonLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonExit)
                    .addComponent(buttonLogIn))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
// TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_buttonExitActionPerformed

private void buttonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogInActionPerformed
// TODO add your handling code here:
    int nFound, nUserType;
    int count = 0;
    
    user = fieldUser.getText();
    pass = fieldPass.getText();
    
    //System.out.println("User Input: "+user);
    //System.out.println("Pass Input: "+pass);
    
   // nFound = verifyUserAccount(user,pass); //RETAIN AFTER TEST
    nFound = verifyDummyAccount(user,pass); //REMOVE AFTER TEST
   
    if(nFound==-1){
        jDialog1.setVisible(true);
        jDialog1.setSize(300, 150);
        jDialog1.setLocationRelativeTo(null);
        this.setVisible(false);
        count++;
        if(count==3)
        {
            this.dispose();
        }
        //this.setEnabled(false);
    }
    /*else{
        new AdminApp(nFound, userType).setVisible(true); //REMOVE AFTER TEST
        dispose();
    }*/
   else{
            //new ErrorBox("login successful").setVisible(true);
            //System.out.println("login successful!");
            
            MainInterface mI = new MainInterface();
            mI.setLocationRelativeTo(null);
            mI.setVisible(true);
            mI.setResizable(true);
            mI.setTitle("AG-Coop Loan Management System");
            this.dispose();   
    }
    
}//GEN-LAST:event_buttonLogInActionPerformed

private void ExitChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitChangeActionPerformed
// TODO add your handling code here:
    jDialog1.dispose();
    this.setVisible(true);
    
    //this.setEnabled(true);
}//GEN-LAST:event_ExitChangeActionPerformed

    private void fieldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPassActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
                

            }
        });
    }
    /*
    public int verifyUserAccount(String u, String p){
        int val = -1;
        
        row = db.executeQuery("SELECT * FROM user");
        try {
            
            row.next();
            //System.out.println("size: "+row.size());
            
            for(int k=0; k<row.size(); k++){
               // System.out.println("#"+k+" id:"+row.getString("userId"));
              //  System.out.println("#"+k+" user:"+row.getString("user"));
               // System.out.println("#"+k+" pass:"+row.getString("pass"));
                if(user.equalsIgnoreCase(row.getString("user"))&&pass.equalsIgnoreCase(row.getString("pass"))){
                    val = row.getInt("userId");
                }
                row.next();
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        //System.out.println(val);
        return val;
    }
    */
    public int verifyDummyAccount(String u, String p){ //FOR TESTING ONLY
        int val = -1;
        
        //if(u.equalsIgnoreCase("admin")&&p.equalsIgnoreCase("adminpass")){
        if(u.equalsIgnoreCase("ALCDBA")&&p.equalsIgnoreCase("ALC")){
            userType = 0;
            val=10000;
        }
        else if(u.equalsIgnoreCase("guest")&&p.equalsIgnoreCase("guestpass")){
            userType = 1;
            val=10001;
        }  
        else if(u.equalsIgnoreCase("")&&p.equalsIgnoreCase("")){
            userType = 0;
            val=10000;
        }               
        
        //System.out.println(val);
        return val;
    }
    
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitChange;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonLogIn;
    private javax.swing.JPasswordField fieldPass;
    private javax.swing.JTextField fieldUser;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables


    
}
