/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package maininterface;

import mainaddinterface.AddCashloan;
import mainaddinterface.AddCompany;
import mainaddinterface.AddMember;
import mainaddinterface.AddNonMember;
import mainaddinterface.AddPurchaseGoods;
import mainaddinterface.AddReceipt;
import mainaddinterface.AddSupplier;
import mainprocesses.ProcessBillStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import mainaddinterface.AddGoods;

public class MainInterface extends javax.swing.JFrame {

    ViewCompany vC = new ViewCompany();
    ViewMember vM = new ViewMember();
    ViewSupplier vS = new ViewSupplier();
    ViewLoan vL = new ViewLoan();
    ViewNonMember vNM = new ViewNonMember();
    ViewReceipt vR = new ViewReceipt();
    ViewPurchaseGoods vG = new ViewPurchaseGoods();
    ViewBill vB = new ViewBill();
    ViewCashloan vCL = new ViewCashloan();
    
    AddMember aM = new AddMember();
    AddSupplier aS = new AddSupplier();
    AddCompany aC = new AddCompany();
    AddGoods aP = new AddGoods();
    AddNonMember aNM = new AddNonMember();
    AddCashloan aCL = new AddCashloan();
    
    ProcessBillStatement pB = new ProcessBillStatement();
    
    public MainInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewTab = new javax.swing.JTabbedPane();
        buttonSave = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        buttonEdit = new javax.swing.JButton();
        buttonRefresh = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        labelSearch = new javax.swing.JLabel();
        textSearch = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBillings = new javax.swing.JMenu();
        menuCompany = new javax.swing.JMenuItem();
        menuMember = new javax.swing.JMenuItem();
        menuNonMember = new javax.swing.JMenuItem();
        menuSupplier = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuLoans = new javax.swing.JMenuItem();
        menuCashloan = new javax.swing.JMenuItem();
        menuGoods = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuReceipt = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuStatement = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuCloseTab = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        viewTab.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        viewTab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                viewTabStateChanged(evt);
            }
        });
        viewTab.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                viewTabComponentAdded(evt);
            }
        });

        buttonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        buttonSave.setToolTipText("Add");
        buttonSave.setEnabled(false);
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        buttonEdit.setToolTipText("Edit");
        buttonEdit.setEnabled(false);
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        buttonRefresh.setToolTipText("Refresh");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });

        buttonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        buttonDelete.setToolTipText("Delete");
        buttonDelete.setEnabled(false);
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        labelSearch.setText("Search:");
        labelSearch.setEnabled(false);

        textSearch.setEnabled(false);

        buttonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifier.png"))); // NOI18N
        buttonSearch.setToolTipText("Search");
        buttonSearch.setEnabled(false);
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        menuBillings.setText("File");

        menuCompany.setText("Company");
        menuCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCompanyActionPerformed(evt);
            }
        });
        menuBillings.add(menuCompany);

        menuMember.setText("Member");
        menuMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMemberActionPerformed(evt);
            }
        });
        menuBillings.add(menuMember);

        menuNonMember.setText("Non-Member");
        menuNonMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNonMemberActionPerformed(evt);
            }
        });
        menuBillings.add(menuNonMember);

        menuSupplier.setText("Supplier");
        menuSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSupplierActionPerformed(evt);
            }
        });
        menuBillings.add(menuSupplier);
        menuBillings.add(jSeparator6);

        jMenuItem2.setText("Billings");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuBillings.add(jMenuItem2);

        jMenuBar1.add(menuBillings);

        jMenu5.setText("Transaction");

        menuLoans.setText("Loans");
        menuLoans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoansActionPerformed(evt);
            }
        });
        jMenu5.add(menuLoans);

        menuCashloan.setText("Cashloan");
        menuCashloan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCashloanActionPerformed(evt);
            }
        });
        jMenu5.add(menuCashloan);

        menuGoods.setText("Goods");
        menuGoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGoodsActionPerformed(evt);
            }
        });
        jMenu5.add(menuGoods);
        jMenu5.add(jSeparator5);

        menuReceipt.setText("Official Receipt");
        menuReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReceiptActionPerformed(evt);
            }
        });
        jMenu5.add(menuReceipt);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Reports");

        jMenuItem1.setText("jMenuItem1");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Process");

        menuStatement.setText("Bill Statement");
        menuStatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStatementActionPerformed(evt);
            }
        });
        jMenu4.add(menuStatement);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Close");

        menuCloseTab.setText("Close Tab");
        menuCloseTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCloseTabActionPerformed(evt);
            }
        });
        jMenu3.add(menuCloseTab);
        jMenu3.add(jSeparator1);

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu3.add(menuExit);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewTab)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(labelSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 692, Short.MAX_VALUE)
                        .addComponent(buttonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewTab, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator3)
                        .addComponent(jSeparator4)
                        .addComponent(buttonSearch)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelSearch)
                        .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCompanyActionPerformed

        viewTab.addTab("Company", vC);
        vC.getList(0,"");
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCompanyActionPerformed

    private void menuCloseTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCloseTabActionPerformed

        if(viewTab.getSelectedComponent() != null)
        {
            viewTab.remove(viewTab.getSelectedIndex());
            if(viewTab.getSelectedComponent() == null)
            {
                buttonEdit.setEnabled(false);
                buttonDelete.setEnabled(false);
                buttonSave.setEnabled(false);
                buttonSearch.setEnabled(false);
                textSearch.setEnabled(false);
                labelSearch.setEnabled(false);
            }
        }
        
        else
            JOptionPane.showMessageDialog(null, "Error: No tab to close", "Error", JOptionPane.ERROR_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCloseTabActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        this.formWindowClosing(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuExitActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed

        String agcoopCompany = "maininterface.ViewCompany";
        String agcoopMember = "maininterface.ViewMember";
        String agcoopSupplier = "maininterface.ViewSupplier";
        String agcoopNonMember = "maininterface.ViewNonMember";
        String agcoopLoan = "maininterface.ViewLoan";
        String agcoopReceipt = "maininterface.ViewReceipt";
        String agcoopGoods = "maininterface.ViewPurchaseGoods";
        String agcoopCashloan = "maininterface.ViewCashloan";
        
        try{
            if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopCompany))
            { 
                aC.reset();
                aC.passThrough();
                aC.setVisible(true);
                aC.setLocationRelativeTo(null);
                aC.setTitle("Add Company - Information");
                aC.setResizable(false);  
            }
        
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopMember))
            {
                aM.reset();
                aM.passThrough();
                aM.setVisible(true);
                aM.setLocationRelativeTo(null);
                aM.setTitle("Add Member - Information");
                aM.setResizable(false);
            }
        
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopSupplier))
            {
                aS.reset();
                aS.passThrough();
                aS.setVisible(true);
                aS.setLocationRelativeTo(null);
                aS.setTitle("Add Supplier - Information");
                aS.setResizable(false);
                
            }
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopNonMember))
            {
                aNM.reset();
                aNM.setVisible(true);
                aNM.passThrough();
                aNM.setLocationRelativeTo(null);
                aNM.setTitle("Add Non-Member - Information");
                aNM.setResizable(false);
            }
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopReceipt))
            {
                AddReceipt aR = new AddReceipt();
                aR.setVisible(true);
                aR.setLocationRelativeTo(null);
                aR.setTitle("Add Receipt - Information");
                aR.setResizable(false);
                
            }
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopLoan))
            {
                vL.addLoan();
            }
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopGoods))
            {
                System.out.println("he");
                aP.reset();
                aP.setVisible(true);
                aP.setLocationRelativeTo(null);
                aP.setResizable(false);
                aP.setTitle("Purchase Goods - Information");
            }
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopCashloan))
            {
                vCL.addLoan();
            }
            else
                System.out.println(viewTab.getSelectedComponent().getClass().getName());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error: Add tab to select where to add", "Error - Adding information", JOptionPane.ERROR_MESSAGE); 
        }
        
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void menuMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMemberActionPerformed
        viewTab.addTab("Member", vM);
        vM.getList(0,"");
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMemberActionPerformed

    private void menuSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSupplierActionPerformed

        viewTab.addTab("Supplier", vS);
        vS.getList(0,"");
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSupplierActionPerformed

    private void viewTabComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_viewTabComponentAdded
        buttonEdit.setEnabled(true);
        buttonDelete.setEnabled(true);
        buttonSave.setEnabled(true);
        buttonSearch.setEnabled(true);
        textSearch.setEnabled(true);
        labelSearch.setEnabled(true);
        viewTab.setSelectedIndex(viewTab.getTabCount()-1);
    }//GEN-LAST:event_viewTabComponentAdded

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
        vM.getList(0,"");
        vC.getList(0,"");
        vS.getList(0,"");
        vL.getList(0);
        vNM.getList(0,"");
        vR.getList();   
        //vG.getList();
        vCL.getList(0);
        vB.getList();
        aM.clearCombo();
        aNM.clearCombo();
    }//GEN-LAST:event_buttonRefreshActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed

        String agcoopCompany = "maininterface.viewCompany";
        String agcoopMember = "maininterface.viewMember";
        String agcoopSupplier = "maininterface.viewSupplier";
        String agcoopLoan = "maininterface.viewLoan";
        String agcoopNonMember = "maininterface.viewNonMember";
        String agcoopReceipt = "maininterface.viewReceipt";
        String agcoopGoods = "maininterface.viewGoods";
        String agcoopCashloan = "maininterface.viewCashloan";
        
            int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?", "Delete - Information", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION)
            {  
                try
                {
                    if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopCompany))
                    {
                        vC.deleteCompany();
                        aM.clearCombo();
                        aNM.clearCombo();
                        vC.getList(0,"");
                    }
        
                    else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopMember))
                    {
                        vM.deleteMember();
                        vM.getList(0,"");
                    }
        
                    else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopSupplier))
                    {
                        vS.deleteSupplier();
                        vS.getList(0,"");
                    }
                    
                    else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopLoan))
                    {
                        vL.deleteLoan();
                        vL.getList(0);
                    }
                    else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopNonMember))
                    {
                        
                        vNM.deleteNonMember();
                        
                        vNM.getList(0,"");
                    }
                    else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopReceipt))
                    {
                        vR.deleteReceipt();
                        vR.getList();
                    }
                    else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopGoods))
                    {
                        //vG.deleteGoods();
                        //vG.getList();
                    }
                    else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopCashloan))
                    {
                        vCL.deleteLoan();
                        vCL.getList(0);
                    }
                    
                    
                }
            
                catch (Exception ex)
                {
                    Logger.getLogger(MainInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed

        String agcoopCompany = "maininterface.ViewCompany";
        String agcoopMember = "maininterface.ViewMember";
        String agcoopSupplier = "maininterface.ViewSupplier";
        String agcoopNonMember = "maininterface.ViewNonMember";
        String agcoopLoan = "maininterface.ViewLoan";
        String agcoopGoods = "maininterface.ViewPurchaseGoods";
        String agcoopCashloan = "maininterface.ViewCashloan";
        
        
        try{
            if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopCompany))
            {
                vC.editCompany();
            }
        
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopMember))
            {
                vM.editMember();
            }
        
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopSupplier))
            {
                vS.editSupplier();
            }
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopNonMember))
            {
                vNM.editMember();
            }
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopLoan))
            {
                vL.editLoan();
            }
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopGoods))
            {
                //vG.editGoods();
            }
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopCashloan))
            {
                vCL.editLoan();
            }
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error: Select row to edit", "Error - Edit information", JOptionPane.ERROR_MESSAGE); 
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditActionPerformed

    private void menuLoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoansActionPerformed

        viewTab.add("Loans", vL);
        vL.getList(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLoansActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed

        String searchQuery = textSearch.getText().toUpperCase();
        
        String agcoopCompany = "maininterface.ViewCompany";
        String agcoopMember = "maininterface.ViewMember";
        String agcoopSupplier = "maininterface.ViewSupplier";
        String agcoopNonMember = "maininterface.ViewNonMember";
        String agcoopLoan = "maininterface.ViewLoan";
        String agcoopGoods = "maininterface.ViewPurchaseGoods";
        String agcoopCashloan = "maininterface.ViewCashloan";
        
        try{
            if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopCompany))
            {
                vC.getList(1, searchQuery);
            }
        
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopMember))
            {
                vM.getList(1, searchQuery);
            }
        
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopSupplier))
            {
                vS.getList(1, searchQuery);
            }
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopNonMember))
            {
                vNM.getList(1, searchQuery);
            }                  
        }
        catch(Exception e)
        {
            //JOptionPane.showMessageDialog(null, "Error: Select row to edit", "Error - Edit information", JOptionPane.ERROR_MESSAGE); 
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void menuStatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStatementActionPerformed
        
        viewTab.add("Billing Statement", pB);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_menuStatementActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus

        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Close application", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
            System.exit(0);
        else
            this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void menuNonMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNonMemberActionPerformed
        viewTab.add("Non-Member",vNM);
        vNM.getList(0,"");
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNonMemberActionPerformed

    private void menuReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReceiptActionPerformed
        // TODO add your handling code here:

        viewTab.add("Receipt", vR);
        vR.getList();
        buttonEdit.setEnabled(false);

    }//GEN-LAST:event_menuReceiptActionPerformed

    public void searchEnable()
    {
        labelSearch.setEnabled(true);
        buttonSearch.setEnabled(true);
        textSearch.setEnabled(true); 
    }
    
    public void searchDisable()
    {
        labelSearch.setEnabled(false);
        buttonSearch.setEnabled(false);
        textSearch.setEnabled(false); 
    }
    
    private void viewTabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_viewTabStateChanged

       String agcoopLoan = "maininterface.ViewLoan";
       String agcoopMember = "maininterface.ViewMember";
       String agcoopCompany = "maininterface.ViewCompany";
       String agcoopSupplier = "maininterface.ViewSupplier";
       String agcoopNonMember = "maininterface.ViewNonMember";
       try
       {
            if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopLoan))
            {
                vL.reset();
                this.searchDisable();
            }
            
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopCompany))
            {
                //vC.getList(1, searchQuery);
                this.searchEnable();
            }
        
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopMember))
            {
                //vM.getList(1, searchQuery);
                this.searchEnable();
            }
        
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopSupplier))
            {
                //vS.getList(1, searchQuery);
                this.searchEnable();
            }
            else if(viewTab.getSelectedComponent().getClass().getName().equals(agcoopNonMember))
            {
                //vNM.getList(1, searchQuery);
                this.searchEnable();
            }
            else
                this.searchDisable();
            
            
       }
       catch(Exception e)
       {
           
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTabStateChanged

    private void menuGoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGoodsActionPerformed

        viewTab.add("Goods",vG);
        //vG.getList();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_menuGoodsActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        viewTab.add("Billing List",vB);
        vB.getList();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuCashloanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCashloanActionPerformed

        viewTab.add("Cashloan",vCL);
        vCL.getList(0);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCashloanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JLabel labelSearch;
    private javax.swing.JMenu menuBillings;
    private javax.swing.JMenuItem menuCashloan;
    private javax.swing.JMenuItem menuCloseTab;
    private javax.swing.JMenuItem menuCompany;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuGoods;
    private javax.swing.JMenuItem menuLoans;
    private javax.swing.JMenuItem menuMember;
    private javax.swing.JMenuItem menuNonMember;
    private javax.swing.JMenuItem menuReceipt;
    private javax.swing.JMenuItem menuStatement;
    private javax.swing.JMenuItem menuSupplier;
    private javax.swing.JTextField textSearch;
    private javax.swing.JTabbedPane viewTab;
    // End of variables declaration//GEN-END:variables
}
