/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package maininterface;

import utilities.DbUtils;
import mainaddinterface.AddNonMember;
import mainconnect.ConnectToDatabaseSys;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class ViewNonMember extends javax.swing.JPanel {

    public ViewNonMember() {
        initComponents();
        listMember.getTableHeader().setReorderingAllowed(false);
    }
    
    ConnectToDatabaseSys paramDB = new ConnectToDatabaseSys();
    public String dbUrl;
    public String dbDriver;
    public String username;
    public String password;
    public Connection conn;
    DbUtils tableUtils = new DbUtils();
    private static String DEFUALT_QUERY = "Select memberid,lastname,firstname,midinit,nonmember.contactno1,nonmember.contactno2,nonmember.email,compname from nonmember inner join company on nonmember.compid = company.compid order by lastname";

    public void getList(int rep, String searchText)
    {
        String tempQuery = "";
        if(rep == 0) {
            tempQuery = DEFUALT_QUERY;
        }
        else if(rep == 1) {
            tempQuery = "select * from (Select memberid,lastname,firstname,midinit,nonmember.contactno1,nonmember.contactno2,nonmember.email,compname from nonmember inner join company on nonmember.compid = company.compid order by lastname) where lastname like '"+searchText+"'";
        }
        //else
          //  tempQuery = "Select * from mydb.bookinformation where Title like '%"+bookTitle+"%';";
        
        //System.out.println(tempQuery);
	Statement stmt = null;       
	this.connect();
	conn = this.getConnection();
                
	try {
            stmt = conn.createStatement();
        }
                
	catch (SQLException e) {
            e.printStackTrace();
        }
		
	ResultSet rs;
	try
        {
            rs = stmt.executeQuery(tempQuery);
            try {
                tableUtils.updateTableModelData((DefaultTableModel) listMember.getModel(), rs, 8);
            } 
            catch (Exception ex) {
                Logger.getLogger(ViewMember.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        catch (SQLException e) {
            e.printStackTrace();
	}
        finally {
            this.disconnect();
        }
        try {
            listMember.setRowSelectionInterval(0, 0);
        }
        catch(Exception e) { }
        
    }
    
    public void deleteNonMember()
    {
        try {
            int index = listMember.getSelectedRow();
            String i = listMember.getValueAt(index, 0).toString();
        
            String query = "delete from nonmember where memberid ="+i;
            ConnectToDatabaseSys connectDB = new ConnectToDatabaseSys();
            connectDB.accessLoopDatabase(query);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Select row to delete", "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }
        
    public void editMember() 
    {
            int index = listMember.getSelectedRow();
            String i = listMember.getValueAt(index, 0).toString();
            AddNonMember aM = new AddNonMember();
            aM.setVisible(true);
            aM.setLocationRelativeTo(null);
            aM.setResizable(false);
            aM.setTitle("Edit Member - Information");
            aM.checkInputEditMember(i);
    }
    
    public void connect()
    {
        dbDriver = paramDB.getDbClass();
        dbUrl = paramDB.getDbUrl();
        password = paramDB.getPassword(); // CHANGE PASSWORD
        username = paramDB.getName();
                
        try {
            Class.forName(dbDriver).newInstance();
            conn = DriverManager.getConnection(dbUrl,username,password);
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
	
    public Connection getConnection()
    {
	return conn;
    }
	
    public void disconnect()
    {
       try {
            conn.close();
       } 
       catch (Exception ex) {
            ex.printStackTrace();
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listMember = new javax.swing.JTable();

        listMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "LASTNAME", "FIRSTNAME", "INITIAL", "CONTACT (1)", "CONTACT (2)", "E-MAIL", "COMPANY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listMember);
        if (listMember.getColumnModel().getColumnCount() > 0) {
            listMember.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listMember;
    // End of variables declaration//GEN-END:variables
}
