
--drop sequence COMPANY_SEQ;
create sequence COMPANY_SEQ start with 1 
increment by 1;

--drop sequence SUPPLIER_SEQ;
create sequence SUPPLIER_SEQ start with 1 
increment by 1;

--drop sequence MEMBER_SEQ;
create sequence MEMBER_SEQ start with 1 
increment by 1;

--drop sequence NONMEMBER_SEQ;
create sequence NONMEMBER_SEQ start with 1 
increment by 1;

--drop sequence LOAN_HDR_SEQ;
create sequence LOAN_HDR_SEQ start with 1 
increment by 1;

--drop sequence LOAN_DTL_SEQ;
create sequence LOAN_DTL_SEQ start with 1 
increment by 1;

--drop sequence CASHLOAN_SEQ;
create sequence CASHLOAN_SEQ start with 1 
increment by 1;

--drop sequence GOODS_SOLD_HDR_SEQ;
create sequence GOODS_SOLD_HDR_SEQ start with 1 
increment by 1;

--drop sequence GOODS_SOLD_DTL_SEQ;
create sequence GOODS_SOLD_DTL_SEQ start with 1 
increment by 1;

--drop sequence BILL_HDR_SEQ;
create sequence BILL_HDR_SEQ start with 1 
increment by 1;

--drop sequence BILL_DTL_SEQ;
create sequence BILL_DTL_SEQ start with 1 
increment by 1;

--drop sequence OR_HDR_SEQ;
create sequence OR_HDR_SEQ start with 1 
increment by 1;

--drop sequence OR_DTL_SEQ;
create sequence OR_DTL_SEQ start with 1 
increment by 1;

--drop sequence PURCHASE_HDR_SEQ;
create sequence PURCHASE_HDR_SEQ start with 1 
increment by 1;

